version: '3.8'

services:
  wishlist-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3013:3013"
    environment:
      - NODE_ENV=production
      - PORT=3013
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/wishlist_db
      - JWT_SECRET=your-secret-key-min-10-chars
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wishlist_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 