version: '3.8'

services:
  order-db:
    image: postgres:14-alpine
    container_name: order-service-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5434:5432" # Using port 5434 to avoid conflicts with other services
    volumes:
      - order-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # The Order Service itself
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    restart: always
    ports:
      - "3006:3006"
    depends_on:
      order-db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=3006
      - DB_HOST=order-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=order_db
      - JWT_SECRET=your-super-secret-jwt-key-min-32-chars-here
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3100

volumes:
  order-db-data: 